include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    no_duplicate_case_values: error
    valid_regexps: error
    cancel_subscriptions: error
    close_sinks: error
    throw_in_finally: error
    avoid_type_to_string: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    missing_required_param: error
    missing_return: error
    missing_enum_constant_in_switch: error
    unused_import: error
    unnecessary_null_comparison: error
    no_default_cases: error
    prefer_if_null_operators: error
    prefer_null_aware_method_calls: error
    prefer_null_aware_operators: error
    unnecessary_null_aware_operator_on_extension_on_nullable: error
    unnecessary_null_checks: error
    use_if_null_to_convert_nulls_to_bools: error
    use_named_constants: error
    avoid_multiple_declarations_per_line: error
    no_logic_in_create_state: error
    avoid_print: error
    unnecessary_parenthesis: error
    unnecessary_statements: error

linter:
  rules:
    avoid_empty_else: true
    avoid_type_to_string: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    throw_in_finally: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_is_not_empty: true
    prefer_typing_uninitialized_variables: true
    always_declare_return_types: true
    unnecessary_new: true
    no_default_cases: true
    curly_braces_in_flow_control_structures: false
    empty_catches: false
    no_leading_underscores_for_local_identifiers: false
    prefer_const_constructors: false
    avoid_print: true
    constant_identifier_names: false
    unnecessary_this: false
    use_key_in_widget_constructors: false
    prefer_conditional_assignment: false
    sized_box_for_whitespace: false
    unnecessary_const: false
    library_private_types_in_public_api: false
    prefer_is_not_operator: false
    avoid_function_literals_in_foreach_calls: false
    unnecessary_string_interpolations: false
    prefer_final_fields: false
    library_prefixes: false
    overridden_fields: false
    avoid_renaming_method_parameters: false
    discarded_futures: false
    prefer_spread_collections: false
    prefer_adjacent_string_concatenation: false
    prefer_const_literals_to_create_immutables: false # hell no
    use_full_hex_values_for_flutter_colors: false
    avoid_void_async: false
    exhaustive_cases: true
    prefer_void_to_null: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_void: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    avoid_multiple_declarations_per_line: true
    no_logic_in_create_state: true
    use_function_type_syntax_for_parameters: true
    prefer_initializing_formals: true
    prefer_mixin: true
    void_checks: true
    unnecessary_parenthesis: true
    use_enums: true
    unnecessary_statements: true
    unnecessary_library_name: false

    # We will want these ASAP, enable and fix 1 by 1.
    avoid_dynamic_calls: false

    # We will want these one day, enable gradually
    always_specify_types: false # want it, but its a pretty big job :(
    avoid_unnecessary_containers: false
    avoid_types_as_parameter_names: false
    avoid_single_cascade_in_expression_statements: false
    prefer_is_empty: false
    prefer_collection_literals: false
    prefer_const_declarations: false
    prefer_interpolation_to_compose_strings: false
    sort_child_properties_last: false
    prefer_const_constructors_in_immutables: false
    prefer_generic_function_type_aliases: false
    use_build_context_synchronously: false
    file_names: false
    prefer_for_elements_to_map_fromIterable: false
    depend_on_referenced_packages: false
    annotate_overrides: false
    unawaited_futures: false # when we do this, make sure we add unawaited if you really want to fire and forget a particular future
