name: parser
description: "Parser making it easy to parse json and get typesafe values from data"
version: 1.0.0
repository: https://github.com/davincium/parser

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

